import pandas as pd
df=pd.read_csv('data.csv')
print(df)
print(df.head(5))
print(df.columns)
print(df.tail(5))
print(df.describe())
print(df.dtypes)
print(df.isnull())
print(df.isnull().any(axis=0))
print(df.isnull().sum())
print(df.fillna(0))
df=df.rename(columns={'sale date':'sale_date'})
print(df)
print(df.head())
print(df.info())
print(df.tail())
print(df.shape)
print(df.isnull)
print(df.dtypes)
print(df.isnull().any(axis=1))
print(df.isnull().any())
print(df.isnull().sum())
print(df.fillna(0))
df['Sales_fillNA']=df['Sales'].fillna(df['Sales'].mean)
print(df)
print(df.dtypes)
df=df.rename(columns={'Date':'Sales Date'})
print(df.head())
print(df.tail())
df['Value_new']=df['Value'].astype(float)
print(df)
df['Value_new']=df['Value'].fillna(df['Value'].mean()).astype(int)
print(df)
df['New Value']=df['Value'].apply(lambda x:x*2)
print(df.head())
print(df.tail())
grouped_mean=df.groupby('Product')['Value'].mean
print(grouped_mean)
grouped_agg=df.groupby("Region")["Value"].agg(["mean","sum","count"])
print(grouped_agg)
df1=pd.DataFrame({"Key":["A","B","C"],"Value1":[1,2,3]})
df2=pd.DataFrame({"Key":["A","B","C"],"Value2":[4,5,6]})
print(df1)
print(df2)
df3=pd.merge(df1,df2,on="Key",how="inner")
print(df3)