import pandas as pd
df=pd.read_csv('data.csv')
print(df)
print(df.head(5))
print(df.columns)
print(df.tail(5))
print(df.describe())
print(df.dtypes)
print(df.isnull())
print(df.isnull().any(axis=0))
print(df.isnull().sum())
print(df.fillna(0))
df=df.rename(columns={'sale date':'sale_date'})
print(df)
print(df.head())
print(df.info())
print(df.tail())
print(df.shape)
print(df.isnull)
print(df.dtypes)
print(df.isnull().any(axis=1))
print(df.isnull().any())
print(df.isnull().sum())
print(df.fillna(0))
df['sales_fillNA']=df['Sales'].fillna(df['Sales'].mean)
print(df)


