import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('data.csv')
print(df.head())
print(df)
print(df.info())
print(df.describe())
print (df.isnull().sum())
df['Date'] = pd.to_datetime(df['Date'])
print(df['Date'])
total_sales = df['Sales'].sum()
print("Total Sales:", total_sales)
average_sales = df['Sales'].mean()
print("Average Sales:", average_sales)
df['month'] = df['Date'].dt.month
monthly_sales = df.groupby('month')['Sales'].sum()
print(monthly_sales)
plt.plot(monthly_sales.index, monthly_sales.values)
plt.title('Monthly Sales')
plt.xlabel('Month')
plt.ylabel('Total Sales')
plt.xticks(monthly_sales.index)
plt.grid()
plt.show()
plt.hist(df['Sales'], bins=10, edgecolor='black')
plt.title('Sales Distribution')
plt.xlabel('Sales')
plt.ylabel('Frequency')
plt.show()
plt.scatter(df['Date'], df['Sales'])
plt.title('Sales Over Time')
plt.xlabel('Date')
plt.ylabel('Sales')
plt.xticks(rotation=45)
plt.grid()
plt.show()