import pandas as pd
import matplotlib.pyplot as plt
df={'product':['freeze','vegetable','dairy','meat','grain','bakery','fruit','snacks','condiments','beverages','other'],
    'sales':[100,150,200,250,300,350,400,450,500,550,600],
    'profit':[20,30,40,50,60,70,80,90,100,110,120],
    'category':['food','food','food','food','food','food','food','food','food','beverage','other']}
df=pd.DataFrame(df)
print(df)
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())
total_sales = df['sales'].sum()
print("Total Sales:", total_sales)
total_profit = df['profit'].sum()
print("Total Profit:", total_profit)
"""plt.bar(df['product'], df['sales'])
plt.title('Sales by Product')
plt.xlabel('Product')
plt.ylabel('Sales')
plt.xticks(rotation=45)
plt.grid()
plt.show()
plt.scatter(df['sales'], df['profit'])
plt.title('Sales vs Profit')
plt.xlabel('Sales')
plt.ylabel('Profit')
plt.grid()
plt.show()"""
print(df)
print(df.isnull().sum())
print(type(df))
df1=df.groupby('category')['sales'].sum()
print(df1)
df2=df['category'].sort_values(ascending=False)
print(df2)
df3=df['profit'].unique()
print(df3)
df4=df['category'].unique()
print(df4)
df5=df['product'].unique()
print(df5)
df6=df.groupby('profit')['sales'].mean()
print(df6)
df7=df.groupby(['product','profit'])['sales'].agg('mean')
print(df7)
df8=df.groupby('product')['sales'].count()
print(df8)