import pandas as pd
import matplotlib.pyplot as plt
df={'product_id':['p001','p002','p003','p004','p005','p006','p007','p008','p009','p010'],
    'product_name':['wireless mouse','laptop','keyboard','monitor','printer','webcam','headphones','speakers','external hard drive','usb flash drive'],
    'category':['electronics','electronics','electronics','electronics','electronics','electronics','electronics','electronics  ','electronics','electronics'],
    'unit':[10,5,15,8,3,12,20,7,4,25],
    'price':[25.99,999.99,49.99,199.99,149.99,89.99,59.99,129.99,79.99,19.99],
    'sales':[259.90,4999.95,749.85,1599.92,449.97,1079.88,1199.80,909.93,319.96,499.75],'units_sold':[10,5,15,8,3,12,20,7,4,25],''
    'region':['North America','Europe','Asia','North America','Europe','Asia','North America','Europe','Asia','North America']}
df=pd.DataFrame(df)
print(df)
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())
total_sales = df['sales'].sum()
print("Total Sales:", total_sales)
total_units_sold = df['units_sold'].sum()
print("Total Units Sold:", total_units_sold)
plt.bar(df['product_name'], df['sales'])
plt.title('Sales by Product')
plt.xlabel('Product Name')
plt.ylabel('Sales')
plt.xticks(rotation=45)
plt.grid()
plt.show()
plt.scatter(df['units_sold'], df['sales'])
plt.title('Units Sold vs Sales')
plt.xlabel('Units Sold')
plt.ylabel('Sales')
plt.grid()
plt.show()
plt.hist(df['sales'], bins=10)
plt.title('Distribution of Sales')
plt.xlabel('Sales')
plt.ylabel('Frequency')
plt.grid()
plt.show()
plt.boxplot(df['sales'])
plt.title('Box Plot of Sales')
plt.ylabel('Sales')
plt.grid()
plt.show()
plt.pie(df['sales'], labels=df['product_name'], autopct='%1.1f%%')
plt.title('Sales Distribution by Product')
plt.axis('equal')
plt.show()
df['category'] = df['category'].str.strip()
category_sales = df.groupby('category')['sales'].sum()  
plt.bar(category_sales.index, category_sales.values)
plt.title('Sales by Category')
plt.xlabel('Category')
plt.ylabel('Sales')
plt.xticks(rotation=45)
plt.grid()
plt.show()
df['region'] = df['region'].str.strip()
region_sales = df.groupby('region')['sales'].sum()
plt.bar(region_sales.index, region_sales.values)
plt.title('Sales by Region')    
plt.xlabel('Region')
plt.ylabel('Sales')
plt.xticks(rotation=45)
plt.grid()
plt.show()
highest_sales_product = df.loc[df['sales'].idxmax()]
print("Product with Highest Sales:")
print(highest_sales_product)
lowest_sales_product = df.loc[df['sales'].idxmin()]
print("Product with Lowest Sales:")
print(lowest_sales_product)
average_sales = df['sales'].mean()
print("Average Sales:", average_sales)
print(type(df))
df1=df.groupby('price')['sales'].sum()
print(df1)
df2=df['sales'].mean()
print(df2)
df3=pd.pivot_table(df,values='sales',index='category',aggfunc='sum')
print(df3)




