import pandas as pd
import matplotlib.pyplot as plt
df={'student_id':['s001','s002','s003','s004','s005','s006','s007','s008','s009','s010'],
    'student_name':['Alice','Bob','Charlie','David','Eve','Frank','Grace','Heidi','Ivan','Judy'],
    'age':[20,21,22,23,24,25,26,27,28,29],
    'grade':[85,90,78,92,88,95,80,91,87,89]}
df=pd.DataFrame(df)
print(df)
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())
average_grade = df['grade'].mean()
print("Average Grade:", average_grade)
plt.bar(df['student_name'], df['grade'])
plt.title('Grades by Student')
plt.xlabel('Student Name')
plt.ylabel('Grade')
plt.xticks(rotation=45)
plt.grid()
plt.show()
plt.scatter(df['age'], df['grade'])
plt.title('Age vs Grade')
plt.xlabel('Age')
plt.ylabel('Grade')
plt.grid()
plt.show()
plt.hist(df['grade'], bins=10)
plt.title('Distribution of Grades')
plt.xlabel('Grade')
plt.ylabel('Frequency')
plt.grid()
plt.show()
plt.boxplot(df['grade'])
plt.title('Box Plot of Grades')
plt.ylabel('Grade')
plt.grid()
plt.show()
plt.pie(df['grade'], labels=df['student_name'], autopct='%1.1f%%')
plt.title('Grade Distribution by Student')
plt.axis('equal')
plt.show()
highest_grade_student = df.loc[df['grade'].idxmax()]
print("Student with Highest Grade:")
print(highest_grade_student)
lowest_grade_student = df.loc[df['grade'].idxmin()]
print("Student with Lowest Grade:")
print(lowest_grade_student)
print("Students with Grade Above 90:")
print(df[df['grade'] > 90])
print("Students with Grade Below 80:")
print(df[df['grade'] < 80])
print(df)
print(df[df['grade']>70])
print('student with grade above 70:')


