import numpy as np
import pandas as pd
df=pd.read_csv('train.csv')
print(df.head())
print(df)
print(df.tail())
print(df.describe())
print(df.isnull().sum())
print(df.fillna(0))
df=df.dropna()
print(df)
total_sales=df['Sales'].sum()
print(total_sales)
category_sales=df.groupby('Category')['Sales'].sum()
print(category_sales)
top_products=df.groupby('Product Name')['Sales'].sum()
print(top_products)