import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('train.csv')
print(df.head())
print(df)
print(df.tail())
print(df.describe())
print(df.isnull().sum())
print(df.fillna(0))
df=df.dropna()
print(df)
total_sales=df['Sales'].sum()
print(total_sales)
category_sales=df.groupby('Category')['Sales'].sum()
print(category_sales)
top_products=df.groupby('Product Name')['Sales'].sum()
print(top_products)
sales_by_region=df.groupby('Region')['Sales'].sum()
print(sales_by_region)
avg_sales=np.mean(df['Sales'])
print(avg_sales)
std_sales=np.std(df['Sales'])
print(std_sales)
category_sales.plot(kind='line')
plt.show()
top_products.plot(kind='line')
plt.show()
sales_by_region.plot(kind='line')
plt.show()