import pandas as pd
from io import StringIO
Data='{"employee_name":"prema","email":"singh@gmail.com","job_profile":[{"title1":"team_lead","title2":"data_analyst"}]}'
df=pd.read_json(StringIO(Data))
print(df)
print(type(df))
df1=df.to_json(orient='records')
print(df1)
print(type(df1))
print(df['employee_name'])
print(df['email'])
print(df['job_profile'])
print(df['job_profile'][0])
print(df['job_profile'][0]['title1'])
print(df['job_profile'][0]['title2'])
print(df['job_profile'][0].keys()) 
print(df['job_profile'][0].values()) 
print(df['job_profile'][0].items()) 
print(df['job_profile'][0].get('title1'))
print(df['job_profile'][0].get('title2'))
print(df['job_profile'][0].get('title3'))
print(df['job_profile'][0].get('title3','Not Found'))
print(df)
df2=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)
print(df2)
print(df2.head())
print(df2.columns)
print(df2.tail())
df.to_csv("output.csv",index=False)
df2.to_csv("wine_data.csv",index=False)
print("DataFrames have been saved to CSV files.")
print(df)
print(df2)
print(df2.describe())
print(df2.info())
print(df2.shape)
print(df2.dtypes)
print(df2.isnull().sum())
print(df2[0].value_counts())
print(df2[1].value_counts())
print(df2[2].value_counts())
print(df2[3].value_counts())